#!/bin/bash

which convert i3lock import  > /dev/null 2>&1

if [ $? != 0 ]
then
    echo -ne "Dependencies are not satisfied\n"
    exit 1
else
    echo -ne "Dependencies are satisfied\n"
    exit 0
fi
